---
title: "Education Attrition Chloropleths"
author: "Miles McBain"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(tmap)
library(rmapshaper)
library(grid)
```

## Load

```{r}
qld_cohort <-
  read_csv("./data/qld_highschool_cohorts_geo.csv")

qld_cohort
```

## Electoral Summary

### Data source

ABS state electorate boundaries in ESRI shapefile format. 2017 release.

http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1270.0.55.003July%202017?OpenDocument

```{r}
state_shapes <-
 read_sf(dsn = "./data/state_shapes")

plot(state_shapes)

state_shapes %>%
  head()

```

The shapes are quite detailed, not really needed. Downsample?

```{r}
## need to transform to use st_simplify
## doesn't work with lat long data apparently.
## using http://spatialreference.org/ref/epsg/gda94-geoscience-australia-lambert/
state_shapes <- st_transform(state_shapes, crs = 3112)

simplified_shapes <- ms_simplify(state_shapes)
```

Filter down to just QLD electorates.

```{r}
## filter down to SED_NAME17 in QLD cohort data
simplified_shapes_qld <-
  simplified_shapes %>%
  semi_join(select(qld_cohort, state_electorate),
            by = c(SED_NAME17 = "state_electorate"))

```

### Summarisation

```{r}
qld_yr10_cohort_attrition <- 
  qld_cohort %>%
  filter(grade == 10) %>%
  group_by(state_electorate) %>%
  summarise(prop10 = sum(ft_enrolments) / sum(initial_enrolments))

```

### Visualisation

```{r}
seq_bbox <-
  st_bbox(c(ymin = -3330667.5393, xmin = 1802106.0528,
            ymax = -3211413.1917,xmax =1913589.6739),
          crs = st_crs(3112))

qld_map <-
  simplified_shapes_qld %>%
  left_join(qld_yr10_cohort_attrition,
            by = c(SED_NAME17 = "state_electorate") ) %>%
  tm_shape() +
  tm_polygons(col = "prop10",
              palette = "plasma",
              title = "2 yr cohort survival"
              ) +
  tm_shape(st_as_sfc(seq_bbox)) +
  tm_borders(col = "black",
             lwd = 2) +
  tm_layout(legend.show = TRUE,
            legend.position = c("left", "top") )

qld_map


seq_map <-
  simplified_shapes_qld %>%
  left_join(qld_yr10_cohort_attrition,
            by = c(SED_NAME17 = "state_electorate") ) %>%
  tm_shape(bbox = seq_bbox) +
  tm_polygons(col = "prop10",
              palette = "plasma"
              ) +
  tm_layout(legend.show = FALSE)

qld_map
print(seq_map, vp = viewport(0.635, 0.83, width = 0.3, height = 0.3))
```

## Statistical Area 2 Summary

## Reproducibility

```{r}
## datetime
Sys.time() 

## repository
git2r::repository()

## session info
sessionInfo
```
